"use client";

import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { LayoutDashboard, Columns3, CalendarDays, BriefcaseBusiness, HardHat, Search, Plus, ArrowUpRight, RefreshCw, Download, List, Phone, Mail, MapPin, FileText, X, LogOut, Menu, Users, Clock, CheckCircle2, ShieldCheck, ChevronRight, StickyNote, PhoneCall, Archive, Check, LockKeyhole } from 'lucide-react';
import { STAGES, PROFESSIONS, EXPERIENCE, AVAILABILITY, CONTACTS, PRIORITIES, type Candidate, type CandidateInput, type Stage } from '@/lib/recruitment-types';

type Tab='dashboard'|'leads'|'calendar'|'placements';
const stageColors=['#3b82f6','#8b5cf6','#06b6d4','#f59e0b','#6366f1','#10b981','#94a3b8'];
const dateText=(date:string)=>date?new Intl.DateTimeFormat('pt-PT',{dateStyle:'short',timeStyle:'short'}).format(new Date(date)):'—';
const dayKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const toLocal=(date:string)=>{if(!date)return '';const d=new Date(date);return `${dayKey(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;};
const normal=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const blank:CandidateInput={nome:'',telefone:'',email:'',localidade:'',profissao:'Pedreiro',experiencia:'Menos de 1 ano',cartaConducao:'Não',transporteProprio:'Não',disponibilidade:'Imediata'};
async function request(url:string,options:RequestInit={}) {
 const response=await fetch(url,{...options,cache:'no-store',headers:{...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}});
 const data=await response.json();
 if(!response.ok)throw Object.assign(new Error(data.error||'Não foi possível concluir a operação.'),{status:response.status});return data;
}
function Badge({stage}:{stage:Stage}){return <span className="crm-badge" style={{color:stageColors[STAGES.indexOf(stage)],background:stageColors[STAGES.indexOf(stage)]+'13'}}>{stage}</span>;}
function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const el=ref.current;el?.showModal();return()=>el?.close();},[]);
 return <dialog ref={ref} className={`crm-dialog ${wide?'crm-dialog-wide':''}`} onCancel={e=>{e.preventDefault();onClose();}} aria-label={title}><header className="crm-modal-head"><h2>{title}</h2><button className="crm-icon" onClick={onClose} aria-label="Fechar"><X size={20}/></button></header>{children}</dialog>;
}
function ProfileFields({value,set}:{value:CandidateInput;set:(v:CandidateInput)=>void}){
 const update=(key:keyof CandidateInput,v:string)=>set({...value,[key]:v});
 return <div className="crm-form-grid">{(['nome','telefone','email','localidade'] as const).map((k,i)=><label key={k}>{['Nome','Telefone','Email','Localidade'][i]}<input required maxLength={k==='email'?254:160} type={k==='email'?'email':k==='telefone'?'tel':'text'} value={value[k]} onChange={e=>update(k,e.target.value)}/></label>)}
 {([['profissao','Profissão / Especialidade',PROFESSIONS],['experiencia','Experiência',EXPERIENCE],['cartaConducao','Carta de condução',['Sim','Não']],['transporteProprio','Transporte próprio',['Sim','Não']],['disponibilidade','Disponibilidade',AVAILABILITY]] as const).map(([key,label,options])=><label key={key}>{label}<select value={value[key]} onChange={e=>update(key,e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>)}
 </div>;
}
function NewCandidate({onClose,onCreated}:{onClose:()=>void;onCreated:(c:Candidate)=>void}){
 const [form,setForm]=useState<CandidateInput>({...blank});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const key=useRef(crypto.randomUUID());
 const submit=async(e:FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const data=await request('/api/crm/leads',{method:'POST',body:JSON.stringify(form),headers:{'Idempotency-Key':key.current}});onCreated(data.lead);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Modal title="Adicionar candidato" onClose={onClose}><form onSubmit={submit} className="crm-modal-body"><p className="crm-muted">Registo manual de um profissional. O consentimento não é registado automaticamente.</p><ProfileFields value={form} set={v=>{key.current=crypto.randomUUID();setForm(v);}}/>{error&&<p role="alert" className="crm-error">{error}</p>}<footer className="crm-modal-actions"><button type="button" className="crm-button" onClick={onClose}>Cancelar</button><button className="crm-button primary" disabled={busy}>{busy?'A guardar…':'Guardar candidato'}</button></footer></form></Modal>;
}
function CandidateDetail({candidate,onClose,onSave}:{candidate:Candidate;onClose:()=>void;onSave:(id:string,version:number,patch:Record<string,unknown>)=>Promise<void>}){
 const [section,setSection]=useState<'profile'|'history'>('profile');const [editing,setEditing]=useState(false);const [profile,setProfile]=useState<CandidateInput>({...candidate});
 const [stage,setStage]=useState(candidate.stage);const [contact,setContact]=useState(candidate.contact);const [priority,setPriority]=useState(candidate.priority);const [nextContact,setNextContact]=useState(toLocal(candidate.nextContact));const [company,setCompany]=useState(candidate.company);const [opportunity,setOpportunity]=useState(candidate.opportunity);
 const [activityType,setActivityType]=useState<'note'|'call'|'interview'>('note');const [text,setText]=useState('');const [result,setResult]=useState('Contactado');const [scheduled,setScheduled]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [saved,setSaved]=useState('');
 const save=async(patch:Record<string,unknown>)=>{if(busy)return false;setBusy(true);setError('');setSaved('');try{await onSave(candidate.id,candidate.version,patch);setSaved('Alterações guardadas.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}};
 const saveManagement=async(e:FormEvent)=>{e.preventDefault();await save({stage,contact,priority,nextContact:nextContact?new Date(nextContact).toISOString():'',company,opportunity});};
 const saveActivity=async(e:FormEvent)=>{e.preventDefault();if(await save({activity:{type:activityType,text,result,scheduledAt:scheduled?new Date(scheduled).toISOString():''}})){setText('');setScheduled('');if(activityType==='call')setContact(result as typeof contact);if(activityType==='interview')setStage('Entrevista');}};
 const fields=[['Email',candidate.email],['Telefone',candidate.telefone],['Localidade',candidate.localidade],['Profissão',candidate.profissao],['Anos de experiência',candidate.experiencia],['Carta de condução',candidate.cartaConducao],['Transporte próprio',candidate.transporteProprio],['Disponibilidade',candidate.disponibilidade]];
 return <Modal title="Ficha do candidato" onClose={onClose} wide><div className="crm-modal-body"><div className="crm-person"><div className="crm-avatar large">{candidate.nome.slice(0,1)}</div><div><p className="crm-eyebrow">{candidate.reference} · {candidate.source}</p><h2>{candidate.nome}</h2><p className="crm-muted">{candidate.profissao} · {candidate.localidade}</p></div><Badge stage={candidate.stage}/></div>
 <div className="crm-contact-actions"><a className="crm-button" href={`tel:${candidate.telefone}`}><Phone size={15}/> Telefonar</a><a className="crm-button" href={`mailto:${candidate.email}`}><Mail size={15}/> Email</a>{candidate.resume?<a className="crm-button" href={`/api/crm/leads/${candidate.id}/curriculo`}><Download size={15}/> Currículo</a>:<span className="crm-muted">Sem currículo anexado</span>}<button className="crm-button" onClick={()=>{setSection('history');setActivityType('call');}}><PhoneCall size={15}/> Registar chamada</button></div>
 <div className="crm-subtabs"><button className={section==='profile'?'active':''} onClick={()=>setSection('profile')}>Perfil e acompanhamento</button><button className={section==='history'?'active':''} onClick={()=>setSection('history')}>Histórico <span>{candidate.activities.length}</span></button></div>
 {error&&<p className="crm-error" role="alert">{error}</p>}{saved&&<p className="crm-success" role="status">{saved}</p>}
 {section==='profile'?<><div className="crm-section-head"><h3>Informações da candidatura</h3><button className="crm-text-button" onClick={()=>{setProfile({...candidate});setEditing(!editing);}}>{editing?'Cancelar edição':'Editar perfil'}</button></div>
 {editing?<form onSubmit={async e=>{e.preventDefault();if(await save({profile}))setEditing(false);}}><ProfileFields value={profile} set={setProfile}/><button className="crm-button primary" disabled={busy}>Guardar perfil</button></form>:<dl className="crm-facts">{fields.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}
 {candidate.resume&&<div className="crm-resume"><FileText size={22}/><div><strong>{candidate.resume.name}</strong><small>{(candidate.resume.size/1024).toFixed(1)} KB · Anexado à candidatura</small></div><a href={`/api/crm/leads/${candidate.id}/curriculo`} className="crm-icon" aria-label="Descarregar currículo"><Download size={18}/></a></div>}
 <form onSubmit={saveManagement} className="crm-management"><h3>Acompanhamento</h3><div className="crm-form-grid"><label>Fase<select value={stage} onChange={e=>setStage(e.target.value as Stage)}>{STAGES.map(s=><option key={s}>{s}</option>)}</select></label><label>Contacto<select value={contact} onChange={e=>setContact(e.target.value as typeof contact)}>{CONTACTS.map(s=><option key={s}>{s}</option>)}</select></label><label>Prioridade<select value={priority} onChange={e=>setPriority(e.target.value as typeof priority)}>{PRIORITIES.map(s=><option key={s}>{s}</option>)}</select></label><label>Próximo contacto<input type="datetime-local" value={nextContact} onChange={e=>setNextContact(e.target.value)}/></label><label>Empresa<input value={company} maxLength={250} onChange={e=>setCompany(e.target.value)} placeholder="Empresa associada"/></label><label>Oportunidade / Obra<input value={opportunity} maxLength={250} onChange={e=>setOpportunity(e.target.value)} placeholder="Função ou obra"/></label></div><button className="crm-button primary" disabled={busy}>{busy?'A guardar…':'Guardar acompanhamento'}</button></form>
 <div className="crm-consent"><ShieldCheck size={18}/><div><strong>{candidate.consent?'Consentimento registado':'Consentimento não registado'}</strong><p>{candidate.consentAt?`${dateText(candidate.consentAt)} · ${candidate.consentVersion}`:'Este candidato foi adicionado manualmente.'}</p>{candidate.consentText&&<details><summary>Ver autorização</summary><p>{candidate.consentText}</p></details>}<p>Entrada: {dateText(candidate.createdAt)} · Atualizado: {dateText(candidate.updatedAt)}</p></div></div>
 </>:<><form onSubmit={saveActivity} className="crm-note-form"><div className="crm-segment"><button type="button" className={activityType==='note'?'active':''} onClick={()=>setActivityType('note')}><StickyNote size={15}/> Nota</button><button type="button" className={activityType==='call'?'active':''} onClick={()=>setActivityType('call')}><PhoneCall size={15}/> Chamada</button><button type="button" className={activityType==='interview'?'active':''} onClick={()=>setActivityType('interview')}><CalendarDays size={15}/> Entrevista</button></div>
 {activityType==='call'&&<label>Resultado<select value={result} onChange={e=>setResult(e.target.value)}>{CONTACTS.slice(1).map(r=><option key={r}>{r}</option>)}</select></label>}
 {activityType==='interview'&&<label>Data e hora da entrevista<input type="datetime-local" required value={scheduled} onChange={e=>setScheduled(e.target.value)}/></label>}
 <label>{activityType==='interview'?'Local / ligação e notas':'Notas'}<textarea required maxLength={12000} rows={4} value={text} onChange={e=>setText(e.target.value)} placeholder="Escreve aqui as informações relevantes…"/></label><button className="crm-button primary" disabled={busy}>{busy?'A guardar…':activityType==='interview'?'Agendar entrevista':activityType==='call'?'Guardar chamada':'Guardar nota'}</button></form>
 <div className="crm-timeline">{candidate.activities.length===0?<p className="crm-muted">Ainda não há registos. Adiciona a primeira nota ou chamada.</p>:candidate.activities.map(a=><article key={a.id}><span className="crm-timeline-dot"/><div className="crm-section-head"><strong>{({note:'Nota',call:'Chamada',interview:'Entrevista',stage:'Alteração de fase',update:'Perfil atualizado'})[a.type]}</strong><time>{dateText(a.at)}</time></div>{a.result&&<span className="crm-chip">{a.result}</span>}{a.scheduledAt&&<p><CalendarDays size={14}/> {dateText(a.scheduledAt)} · {a.status}</p>}<p className="crm-prewrap">{a.text}</p>{a.type==='interview'&&<div className="crm-contact-actions"><button disabled={busy||a.status==='Realizada'} className="crm-button small" onClick={()=>save({interview:{id:a.id,status:'Realizada'}})}>Marcar realizada</button><button disabled={busy||a.status==='Cancelada'} className="crm-button small" onClick={()=>save({interview:{id:a.id,status:'Cancelada'}})}>Cancelar entrevista</button></div>}</article>)}</div>
 </>}
 </div></Modal>;
}

export default function RecruitmentCRM(){
 const [auth,setAuth]=useState<'loading'|'out'|'in'>('loading');const [password,setPassword]=useState('');const [loginError,setLoginError]=useState('');const [logging,setLogging]=useState(false);
 const [leads,setLeads]=useState<Candidate[]>([]);const [tab,setTab]=useState<Tab>('dashboard');const [view,setView]=useState<'board'|'table'>('board');const [sidebar,setSidebar]=useState(false);const [search,setSearch]=useState('');const [stageFilter,setStageFilter]=useState('');const [professionFilter,setProfessionFilter]=useState('');const [locationFilter,setLocationFilter]=useState('');const [availabilityFilter,setAvailabilityFilter]=useState('');const [priorityFilter,setPriorityFilter]=useState('');const [contactFilter,setContactFilter]=useState('');
 const [selected,setSelected]=useState('');const [newOpen,setNewOpen]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [lastSync,setLastSync]=useState('');const [agendaDate,setAgendaDate]=useState('');const [dragging,setDragging]=useState('');const [moving,setMoving]=useState(false);
 const refresh=useCallback(async()=>{setLoading(true);try{const data=await request('/api/crm/leads');setLeads(data.leads);setLastSync(new Date().toISOString());setError('');}catch(e){if((e as {status?:number}).status===401){setAuth('out');setLeads([]);setSelected('');}else setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{request('/api/crm/session').then(d=>setAuth(d.authenticated?'in':'out')).catch(()=>{setAuth('out');setLoginError('Não foi possível ligar ao servidor.');});},[]);
 useEffect(()=>{if(auth!=='in')return;refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh();},15000);const onFocus=()=>refresh();window.addEventListener('focus',onFocus);return()=>{clearInterval(timer);window.removeEventListener('focus',onFocus);};},[auth,refresh]);
 const login=async(e:FormEvent)=>{e.preventDefault();setLogging(true);setLoginError('');try{await request('/api/crm/login',{method:'POST',body:JSON.stringify({password})});setPassword('');setAuth('in');}catch(e){setLoginError((e as Error).message);}finally{setLogging(false);}};
 const update=async(id:string,version:number,patch:Record<string,unknown>)=>{try{const d=await request(`/api/crm/leads/${id}`,{method:'PATCH',body:JSON.stringify({version,...patch})});setLeads(previous=>previous.map(l=>l.id===id?d.lead:l));}catch(e){if((e as {status?:number}).status===401){setAuth('out');setSelected('');setLeads([]);}if((e as {status?:number}).status===409)await refresh();throw e;}};
 const move=async(id:string,stage:Stage)=>{const lead=leads.find(l=>l.id===id);if(!lead||lead.stage===stage||moving)return;setMoving(true);try{await update(id,lead.version,{stage});}catch(e){setError((e as Error).message);}finally{setMoving(false);setDragging('');}};
 const filtered=useMemo(()=>leads.filter(l=>{
  const q=normal(search.trim());return (!q||normal([l.nome,l.email,l.telefone,l.localidade,l.profissao,l.reference].join(' ')).includes(q))&&(!stageFilter||l.stage===stageFilter)&&(!professionFilter||l.profissao===professionFilter)&&(!locationFilter||l.localidade===locationFilter)&&(!availabilityFilter||l.disponibilidade===availabilityFilter)&&(!priorityFilter||l.priority===priorityFilter)&&(!contactFilter||l.contact===contactFilter)&&(tab!=='placements'||['Contratado','Apresentado à empresa'].includes(l.stage));
 }),[leads,search,stageFilter,professionFilter,locationFilter,availabilityFilter,priorityFilter,contactFilter,tab]);
 const active=leads.filter(l=>l.stage!=='Arquivado');const today=dayKey(new Date());const due=active.filter(l=>l.nextContact&&l.nextContact<=new Date().toISOString());
 const events=useMemo(()=>leads.filter(l=>l.stage!=='Arquivado').flatMap(l=>[...(l.nextContact?[{id:l.id+'-next',lead:l,at:l.nextContact,title:'Próximo contacto',text:l.contact}]:[]),...l.activities.filter(a=>a.type==='interview'&&a.status==='Marcada'&&a.scheduledAt).map(a=>({id:a.id,lead:l,at:a.scheduledAt!,title:'Entrevista',text:a.text}))]).sort((a,b)=>a.at.localeCompare(b.at)),[leads]);
 const selectedLead=leads.find(l=>l.id===selected);
 const resetFilters=()=>{setSearch('');setStageFilter('');setProfessionFilter('');setLocationFilter('');setAvailabilityFilter('');setPriorityFilter('');setContactFilter('');};
 const csv=()=>{const headers=['Referência','Nome','Telefone','Email','Localidade','Profissão','Experiência','Carta de condução','Transporte próprio','Disponibilidade','Fase','Contacto','Prioridade','Empresa','Oportunidade','Próximo contacto','Origem','Entrada','Consentimento','Data do consentimento','Currículo'];const rows=filtered.map(l=>[l.reference,l.nome,l.telefone,l.email,l.localidade,l.profissao,l.experiencia,l.cartaConducao,l.transporteProprio,l.disponibilidade,l.stage,l.contact,l.priority,l.company,l.opportunity,l.nextContact,l.source,l.createdAt,l.consent?'Sim':'Não',l.consentAt||'',l.resume?.name||'']);const cell=(value:string)=>'"'+(/^[=+@\-\t\r]/.test(value)?"'":'')+value.replace(/"/g,'""')+'"';const blob=new Blob(['\uFEFF'+[headers,...rows].map(row=>row.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`candidatos-${today}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const titles={dashboard:'Visão geral',leads:'Candidatos e funil',calendar:'Agenda de recrutamento',placements:'Empresas e colocações'};
 if(auth==='loading')return <div className="crm-root crm-login"><div className="crm-login-card"><HardHat size={32}/><h1>A abrir o CRM…</h1></div></div>;
 if(auth==='out')return <div className="crm-root crm-login"><form className="crm-login-card" onSubmit={login}><div className="crm-login-icon"><HardHat size={28}/></div><span className="crm-eyebrow">CONSTRUÇÃO · RECRUTAMENTO</span><h1>O próximo passo<br/>começa aqui.</h1><p className="crm-muted">Entra para acompanhar candidatos, contactos e oportunidades.</p><label>Palavra-passe do CRM<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} autoFocus/></label>{loginError&&<p role="alert" className="crm-error">{loginError}</p>}<button className="crm-button primary" disabled={logging}><LockKeyhole size={16}/>{logging?'A entrar…':'Entrar no CRM'}</button><small>Acesso reservado à equipa de recrutamento.</small><a href="/" className="crm-text-button">Voltar à landing page <ArrowUpRight size={14}/></a></form></div>;
 return <div className="crm-root">{sidebar&&<button className="crm-sidebar-shade" aria-label="Fechar menu" onClick={()=>setSidebar(false)}/>}
 <aside className={`crm-sidebar ${sidebar?'open':''}`}><div className="crm-brand"><div><HardHat size={22}/></div><span><strong>RECRUTAMENTO CRM</strong><small>PROFISSIONAIS DA CONSTRUÇÃO</small></span><button aria-label="Fechar menu" className="crm-mobile-close" onClick={()=>setSidebar(false)}><X size={19}/></button></div><p className="crm-nav-label">MENU PRINCIPAL</p><nav>{([{id:'dashboard',label:'Dashboard',icon:LayoutDashboard},{id:'leads',label:'Leads / Funil',icon:Columns3},{id:'calendar',label:'Calendário',icon:CalendarDays},{id:'placements',label:'Empresas / Colocações',icon:BriefcaseBusiness}] as const).map(n=><button key={n.id} onClick={()=>{setTab(n.id);setSidebar(false);}} className={tab===n.id?'active':''}><n.icon size={18}/><span>{n.label}</span>{n.id==='leads'&&<b>{leads.length}</b>}{n.id==='calendar'&&events.length>0&&<b>{events.length}</b>}</button>)}</nav><div className="crm-sidebar-bottom"><div className="crm-connection"><span/><div><strong>Landing page ligada</strong><small>Candidaturas e currículos num só lugar</small></div></div><a href="/" target="_blank" rel="noreferrer">Abrir landing page <ArrowUpRight size={16}/></a><button onClick={async()=>{try{await request('/api/crm/logout',{method:'POST'});setAuth('out');setLeads([]);setSelected('');}catch(e){setError((e as Error).message);}}}><LogOut size={16}/> Terminar sessão</button></div></aside>
 <div className="crm-main"><header className="crm-topbar"><button className="crm-icon crm-mobile-menu" aria-label="Abrir menu" onClick={()=>setSidebar(true)}><Menu/></button><div className="crm-breadcrumb">Recrutamento <ChevronRight size={14}/> <strong>{titles[tab]}</strong></div><div className="crm-topbar-right"><span className="crm-sync"><i/>{lastSync?`Atualizado às ${new Date(lastSync).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}`:'A sincronizar'}</span><button className="crm-icon" aria-label="Atualizar candidaturas" disabled={loading} onClick={refresh}><RefreshCw size={17} className={loading?'crm-spin':''}/></button><span className="crm-avatar">RH</span></div></header>
 <main className="crm-content"><div className="crm-page-heading"><div><p className="crm-eyebrow">A TUA REDE DE PROFISSIONAIS</p><h1>{titles[tab]}</h1><p className="crm-muted">{tab==='dashboard'?'Do primeiro contacto à próxima oportunidade.':tab==='calendar'?'Entrevistas e próximos contactos, organizados por data.':tab==='placements'?'Acompanha os perfis apresentados e as contratações.':'Toda a informação de cada candidatura, num único lugar.'}</p></div><button className="crm-button primary" onClick={()=>setNewOpen(true)}><Plus size={18}/> Adicionar candidato</button></div>
 {error&&<div role="alert" className="crm-error">{error} <button onClick={refresh}>Tentar novamente</button></div>}
 {tab==='dashboard'?<><div className="crm-stats">{[{label:'Candidaturas recebidas',value:leads.length,icon:Users,color:'blue',foot:`${leads.filter(l=>dayKey(new Date(l.createdAt))===today).length} recebidas hoje`},{label:'Por contactar',value:active.filter(l=>l.contact==='Por contactar').length,icon:Phone,color:'violet',foot:'À espera do primeiro contacto'},{label:'Contactos em atraso',value:due.length,icon:Clock,color:'amber',foot:'Próximos contactos por realizar'},{label:'Profissionais contratados',value:leads.filter(l=>l.stage==='Contratado').length,icon:CheckCircle2,color:'green',foot:'Oportunidades concretizadas'}].map(s=><article key={s.label} className="crm-stat"><div><span>{s.label}</span><div className={`crm-stat-icon ${s.color}`}><s.icon size={19}/></div></div><strong>{s.value}</strong><small>{s.foot}</small></article>)}</div>
 <div className="crm-dashboard-grid"><section className="crm-panel"><div className="crm-section-head"><div><h2>Funil de recrutamento</h2><p className="crm-muted">Candidaturas por fase</p></div><button className="crm-text-button" onClick={()=>{setTab('leads');resetFilters();}}>Ver funil <ArrowUpRight size={14}/></button></div><div className="crm-stage-chart">{STAGES.map((s,i)=>{const count=leads.filter(l=>l.stage===s).length;return <button key={s} onClick={()=>{resetFilters();setStageFilter(s);setTab('leads');}}><span><i style={{background:stageColors[i]}}/>{s}</span><div><i style={{width:`${leads.length?Math.max(2,count/leads.length*100):0}%`,background:stageColors[i]}}/></div><b>{count}</b></button>;})}</div></section>
 <section className="crm-panel"><div className="crm-section-head"><div><h2>Próximos passos</h2><p className="crm-muted">Contactos e entrevistas</p></div><CalendarDays size={20}/></div>{events.length?events.slice(0,5).map(e=><button className="crm-agenda-mini" key={e.id} onClick={()=>setSelected(e.lead.id)}><div className="crm-date-box"><b>{new Date(e.at).getDate()}</b><span>{new Date(e.at).toLocaleDateString('pt-PT',{month:'short'})}</span></div><div><strong>{e.lead.nome}</strong><p>{e.title} · {new Date(e.at).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}</p></div><ChevronRight size={16}/></button>):<div className="crm-empty small"><CalendarDays/><h3>Agenda livre</h3><p>Marca uma entrevista ou o próximo contacto na ficha de um candidato.</p></div>}</section></div>
 <section className="crm-panel"><div className="crm-section-head"><div><h2>Últimas candidaturas</h2><p className="crm-muted">Recebidas diretamente da landing page</p></div><button className="crm-text-button" onClick={()=>{setTab('leads');setView('table');resetFilters();}}>Ver todas <ArrowUpRight size={14}/></button></div>{leads.length?<CandidateTable leads={leads.slice(0,6)} open={setSelected}/>:<EmptyState/>}</section>
 </>:tab==='calendar'?<section className="crm-panel"><div className="crm-section-head"><h2>Contactos e entrevistas</h2><div className="crm-agenda-filter"><label>Filtrar por dia<input type="date" value={agendaDate} onChange={e=>setAgendaDate(e.target.value)}/></label>{agendaDate&&<button className="crm-button" onClick={()=>setAgendaDate('')}>Todos os dias</button>}</div></div>{events.filter(e=>!agendaDate||dayKey(new Date(e.at))===agendaDate).length?events.filter(e=>!agendaDate||dayKey(new Date(e.at))===agendaDate).map(e=><button key={e.id} className="crm-agenda-row" onClick={()=>setSelected(e.lead.id)}><div className="crm-date-box"><b>{new Date(e.at).getDate()}</b><span>{new Date(e.at).toLocaleDateString('pt-PT',{month:'short'})}</span></div><div><strong>{e.lead.nome}</strong><p>{e.title} · {dateText(e.at)}</p><small>{e.lead.profissao} · {e.lead.localidade}</small></div><span className="crm-chip">{new Date(e.at)<new Date()?'Por concluir':'Agendado'}</span><ChevronRight size={18}/></button>):<div className="crm-empty"><CalendarDays size={34}/><h3>Sem compromissos {agendaDate?'neste dia':'agendados'}</h3><p>Abre uma ficha para marcar uma entrevista ou um próximo contacto.</p></div>}</section>:<>
 <div className="crm-toolbar"><div className="crm-search"><Search size={17}/><input aria-label="Pesquisar candidatos" placeholder="Pesquisar nome, telefone, email ou localidade…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="crm-segment"><button className={view==='board'?'active':''} onClick={()=>setView('board')}><Columns3 size={16}/> Funil</button><button className={view==='table'?'active':''} onClick={()=>setView('table')}><List size={16}/> Listagem</button></div><button className="crm-button" onClick={csv} disabled={!filtered.length}><Download size={16}/> Exportar</button></div>
 <div className="crm-filters"><FilterSelect label="Todas as fases" value={stageFilter} set={setStageFilter} options={STAGES}/><FilterSelect label="Todas as profissões" value={professionFilter} set={setProfessionFilter} options={PROFESSIONS}/><FilterSelect label="Todas as localidades" value={locationFilter} set={setLocationFilter} options={[...new Set(leads.map(l=>l.localidade))].sort()}/><FilterSelect label="Disponibilidade" value={availabilityFilter} set={setAvailabilityFilter} options={AVAILABILITY}/><FilterSelect label="Prioridade" value={priorityFilter} set={setPriorityFilter} options={PRIORITIES}/><FilterSelect label="Contacto" value={contactFilter} set={setContactFilter} options={CONTACTS}/><button className="crm-text-button" onClick={resetFilters}>Limpar filtros</button></div>
 <div className="crm-results"><span><strong>{filtered.length}</strong> {filtered.length===1?'candidato':'candidatos'}</span>{view==='board'&&<small>Arrasta um cartão ou usa o seletor de fase.</small>}</div>
 {view==='table'?<section className="crm-panel no-padding">{filtered.length?<CandidateTable leads={filtered} open={setSelected}/>:<EmptyState filtered={leads.length>0}/>}</section>:<div className="crm-board" aria-label="Funil de recrutamento">{STAGES.filter(s=>!stageFilter||s===stageFilter).filter(s=>tab!=='placements'||['Contratado','Apresentado à empresa'].includes(s)).map(s=><section className="crm-column" key={s} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();move(e.dataTransfer.getData('text/plain')||dragging,s);}}><header style={{borderTopColor:stageColors[STAGES.indexOf(s)]}}><h2>{s}</h2><span>{filtered.filter(l=>l.stage===s).length}</span></header><div className="crm-column-body">{filtered.filter(l=>l.stage===s).map(l=><article className={`crm-candidate-card ${dragging===l.id?'dragging':''}`} key={l.id} draggable={!moving} onDragStart={e=>{e.dataTransfer.setData('text/plain',l.id);setDragging(l.id);}} onDragEnd={()=>setDragging('')}><button className="crm-card-main" onClick={()=>setSelected(l.id)}><div className="crm-card-meta"><span>{l.reference}</span>{l.priority!=='Normal'&&<b className="crm-priority">{l.priority}</b>}</div><h3>{l.nome}</h3><p>{l.profissao}</p><div className="crm-card-place"><MapPin size={13}/>{l.localidade}</div><div className="crm-card-tags"><span>{l.experiencia}</span>{l.resume&&<span><FileText size={12}/> CV</span>}</div><div className="crm-availability"><span className={l.disponibilidade==='Imediata'?'available':''}/>{l.disponibilidade}</div><footer><span>{l.contact}</span><small>{new Date(l.createdAt).toLocaleDateString('pt-PT')}</small></footer></button><select aria-label={`Fase de ${l.nome}`} value={l.stage} disabled={moving} onChange={e=>move(l.id,e.target.value as Stage)}>{STAGES.map(stage=><option key={stage}>{stage}</option>)}</select></article>)}{!filtered.some(l=>l.stage===s)&&<p className="crm-column-empty">Sem candidatos nesta fase</p>}</div></section>)}</div>}
 </>}
 <footer className="crm-footer"><span><ShieldCheck size={13}/> Dados guardados no servidor</span><span>Recrutamento · Construção</span></footer>
 </main></div>
 {newOpen&&<NewCandidate onClose={()=>setNewOpen(false)} onCreated={c=>{setLeads(prev=>[c,...prev.filter(l=>l.id!==c.id)]);setNewOpen(false);setSelected(c.id);}}/>}
 {selectedLead&&<CandidateDetail key={selectedLead.id} candidate={selectedLead} onClose={()=>setSelected('')} onSave={update}/>}
 </div>;
}
function FilterSelect({label,value,set,options}:{label:string;value:string;set:(value:string)=>void;options:readonly string[]}){return <select aria-label={label} value={value} onChange={e=>set(e.target.value)}><option value="">{label}</option>{options.map(o=><option key={o}>{o}</option>)}</select>;}
function EmptyState({filtered=false}:{filtered?:boolean}){return <div className="crm-empty"><Users size={36}/><h3>{filtered?'Nenhum candidato corresponde aos filtros':'Pronto para receber candidaturas'}</h3><p>{filtered?'Experimenta outra pesquisa ou limpa os filtros.':'As candidaturas enviadas na landing page aparecem aqui automaticamente, com todas as informações e o currículo.'}</p>{!filtered&&<a className="crm-button primary" href="/#candidatura" target="_blank" rel="noreferrer">Abrir formulário <ArrowUpRight size={15}/></a>}</div>;}
function CandidateTable({leads,open}:{leads:Candidate[];open:(id:string)=>void}){return <div className="crm-table-scroll"><table className="crm-table"><thead><tr><th>Candidato</th><th>Profissão / Experiência</th><th>Localidade</th><th>Disponibilidade</th><th>Fase</th><th>Currículo</th><th>Entrada</th></tr></thead><tbody>{leads.map(l=><tr key={l.id}><td><button className="crm-table-name" onClick={()=>open(l.id)}><span className="crm-avatar">{l.nome.slice(0,1)}</span><span><strong>{l.nome}</strong><small>{l.telefone}</small></span></button></td><td>{l.profissao}<small>{l.experiencia}</small></td><td>{l.localidade}</td><td>{l.disponibilidade}</td><td><Badge stage={l.stage}/></td><td>{l.resume?<a className="crm-text-button" href={`/api/crm/leads/${l.id}/curriculo`}><FileText size={16}/> Abrir</a>:<span className="crm-muted">—</span>}</td><td>{new Date(l.createdAt).toLocaleDateString('pt-PT')}</td></tr>)}</tbody></table></div>;}
